### ISSUE TITLE
Daily Plot | Change datetime to native python type

### ISSUE THREAD

**Issue by vamseeachanta** [samdansk2/assethold#4]
Daily plot is showing date as string (Assumption)
Daily plot should take date as a native python variable

**Comment by vamseeachanta** [comment]
Example format:
EOD_df.Date = pd.to_datetime(EOD_df.Date, infer_datetime_format=True)

**Comment by samdansk2** [comment]
@vamseeachanta 
Changed the datetime to python type sir, but still no change in plot. There is a problem with axis and should fix that.

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir , 
Tried changing xlim values of Date , still no change , the problem is x tick labels are overlapping , 
i got the solution , but unable to resolve the problem , the solution is below : 
https://stackoverflow.com/questions/26700598/matplotlib-showing-x-tick-labels-overlapping

**Comment by samdansk2** [comment]
@vamseeachanta 
changed the datetime to native python type , now can able to see x ticks , please see below 
![datetime](https://github.com/user-attachments/assets/ef524bcd-fcd8-4afc-a1c6-275969c5f927)
